apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-etcd-2
  labels:
    kubeless: etcd
spec:
  storageClassName: local-storage
  volumeName: pv-loc-sc-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi